spring:
    profiles:
        active:
            -dev
            
---
spring:
    profiles: dev
    application:
        name: my-springcloud-config-dev
        
---
spring:
    profiles: test
    application:
        name: my-springcloud-config-test
        
# 请保存为UTF-8格式